### ISSUE TITLE
NodeGeneric3 - Infos non affichées

### ISSUE THREAD

**Issue by Krelyx** [fets13/Master-plugins#2]
Certaines infos ne s'affichent pas dans le master:
-  la valeur du CRC reste à 0,
-  les data ne sont pas complètes.

[16:5:55] NodeRequestHandler.cpp:125: enter in NodeGeneric3 1/125/1/1
NodesManager::GetNode(125) 110
[16:5:55] Node.cpp:47: 	Dump from NodesManager::SendMsg
[16:5:55] Node.cpp:48: Sender:1 Receptor:125 Type:2 Size:2 CRC:0
[16:5:55] Node.cpp:58: Data Hex:  0x10
[16:5:55] Node.cpp:63: Data Dec:  16

Série Arduino:
Emetteur :1
Recepteur :125
Type :2
Taille :4
CRC :98
Data Hex:  0x10 0x01 0x00
Data Dec:  16 1 0

**Comment by fets13** [comment]
Si je colmprends bien, tu essaies d'envoyere une commande ON sur la sortie 1 ?
Je viens de regarder les points du master.
il me semble que ce ne sont que des pbs d'affichage :  
   - le crc est calculé après l’affichage du debug, il est donc à 0.
   - Il manque 1 data car la taille du crc est incluse dans la taille, donc on affiche jusqu'à (taille -1).

En revanche ce qu'affiche l'arduino Serial n'est pas bon au niveau de la taille. Je vais regarder ça.
Et côté du Node, il dit quoi ?

**Comment by Krelyx** [comment]
Oui, c'est ça; j'envoie une commande ON sur le nid 1.Le master n'affiche ni le CRC et la data[2]: ça peut être gênant par moment.  
La sortie arduino postée précédement est celle du node.
Avec la correction de YdleSerial/ydle.cpp: la taille est corrigée, le node reçoit deux champs de données.
